version: '3'

services:
    database:
      container_name: database
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: bd_leboncoin
        MYSQL_USER: user_test
        MYSQL_PASSWORD: user_test
      ports:
        - '3306:3306'
      volumes:
        - ./mysql:/var/lib/mysql

    php:
      container_name: "php"
      build:
          context: ./php
      environment:
          - APP_SECRET=${APP_SECRET}
      volumes:
          - ${APP_FOLDER}:/var/www
      depends_on:
          - database

    nginx:
      container_name: "nginx"
      build:
          context: ./nginx
      volumes:
          - ${APP_FOLDER}:/var/www
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./logs:/var/log
      depends_on:
          - database
          - php
      ports:
          - "80:80"